[project]
name = "clai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "aiohttp>=3.12.13",
    "dotenv>=0.9.9",
    "rich>=14.0.0",
]
